<?php

namespace Examples\console;

use Om\Console\CliCommand;
use Symfony\Component\Console\Input\InputDefinition;

class TestCliCommand extends CliCommand
{

    protected function registerCliCommand()
    {
        $this->name = "Test";
        $this->command = "test:console";
        $this->help = "test console";
        parent::registerCliCommand(); // TODO: Change the autogenerated stub
    }

}