<?php

namespace Om\Console;

use Om\Console\CliCommand;
use Symfony\Component\Console\Input\InputDefinition;

class TestCliCommand extends CliCommand
{

    protected String $name="Test";

    protected string $command="test:console";

    protected function registerCliCommand()
    {
        parent::registerCliCommand(); // TODO: Change the autogenerated stub
    }

}